### ISSUE TITLE
Be able to generate tones of lengths other than seconds

### ISSUE THREAD

**Issue by ElFeesho** [nisrulz/zentone#3]

**Comment by ElFeesho** [comment]
Maybe consider using `TimeUnit` as an argument to make it explicit what kind of time unit the delay is.

**Comment by nisrulz** [comment]
Good point @ElFeesho. Would update codebase with that.

**Comment by nisrulz** [comment]
The new release doesn't care about the "Duration". It lets the user decided when they want to stop the audio from playing by simply calling `stop()` on the `ZenTone` instance.

Closing as the ticket is irrelevant now.
