### ISSUE TITLE
Remove Duration

### ISSUE THREAD

**Issue by nrbKarlo** [nisrulz/zentone#4]
What a wonderful library. Very easy to use. kudos

Just a suggestion, can we remove the duration? We will just generate the tune on MotionEvent.ACTION_DOWN and stop the tune until the user unpressed the button (MotionEvent.ACTION_UP).

    `  findViewById(R.id.play_tune_button).setOnTouchListener(new View.OnTouchListener() {
            @Override
            public boolean onTouch(View view, MotionEvent motionEvent) {
                if (motionEvent.getAction() == MotionEvent.ACTION_DOWN){
                    Log.w("Pressed", "Button ACTION_DOWN1");               
                    generateSound(261);
                }

                else if (motionEvent.getAction() == MotionEvent.ACTION_UP){
                    Log.w("Pressed", "Button ACTION_UP1");
                    stopSound();
                }
                return false;
            }
        });`

**Comment by nisrulz** [comment]
The new release doesn't care about the "Duration". It lets the user decided when they want to stop the audio from playing by simply calling `stop()` on the `Zentone` instance.

Closing as the ticket is irrelevant now.
