### ISSUE TITLE
Can't generate two frequency at the same

### ISSUE THREAD

**Issue by nrbKarlo** [nisrulz/zentone#5]
Can't generate two tone frequency at the same time

 ZenTone.getInstance().generate(300, 2, 0.5f, toneStoppedListener());

 ZenTone.getInstance().generate(500, 2, 0.5f, toneStoppedListener());

**Comment by nisrulz** [comment]
It was not possible earlier because `ZenTone` was a Singleton. This is changed now with the new release v2.0.0.

Now it is possible to instantiate multiple instances of `ZenTone`.
