### ISSUE TITLE
Big duration makes app crash because OOM

### ISSUE THREAD

**Issue by vitovalov** [nisrulz/zentone#6]
I wanted to play sound for long time period so I tried TimeUnit.MINUTES.toSeconds(100)
That caused OOM because of allocation too much memory.

**Comment by nisrulz** [comment]
@vitovalov thanks for reporting this. I will look into it.

**Comment by nisrulz** [comment]
The new release doesn't care about the "Duration". It lets the user decided when they want to stop the audio from playing by simply calling `stop()` on the `ZenTone` instance.

Closing as the ticket is irrelevant now.
