### ISSUE TITLE
stop() doesn't stop really

### ISSUE THREAD

**Issue by vitovalov** [nisrulz/zentone#7]
In onResume I play a sound. In onStop I call stop(). That has no effect and the sound keeps playing.

**Comment by nisrulz** [comment]
@vitovalov thanks for reporting this. I will look into it.

**Comment by cjpark87** [comment]
I made a pull request to fix this bug.

**Comment by nisrulz** [comment]
A new version v2.0.0 is released. In case the problem still exists, please open a new ticket.
