### ISSUE TITLE
Duration in ms?

### ISSUE THREAD

**Issue by nicklyk** [nisrulz/zentone#9]
Is there any way i could set the duration of the playback to milliseconds?

**Comment by nisrulz** [comment]
This library needs to be updated seriously. It is very outdated. Technically possible to do that via using the [TimeUnit class](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/TimeUnit.html)

If will probably make this update in future, but for now there is no commitment/timeline to do it.

If you think you would want that, you could experiment on your side and maybe also open a PR back to this project :)

**Comment by nicklyk** [comment]
Yeah, i'm not sure i have the technical know-how to do this.

I will surely check it out though.

Thanks for the response, i really appreciate it.

**Comment by nisrulz** [comment]
The new release doesn't care about the "Duration". It lets the user decided when they want to stop the audio from playing by simply calling `stop()` on the `ZenTone` instance.

Closing as the ticket is irrelevant now.
